# Generated by Django 4.2 on 2023-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFriends',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('special_occasions', models.DateField()),
                ('remind_before', models.BooleanField(default=False)),
            ],
        ),
    ]
